### ISSUE TITLE
facetFields not working when loaded on page load

### ISSUE THREAD

**Issue by gehlen** [joosth/wfp-forms#1]
Problem is, facetfields are loaded before datatable data.., so there are no facetfield options to get at that time..

Reproducable by:
- configuring a facetfield as defaultSearchColumn in Config.groovy
- selecting a facetfield and search something, reload page, the facetfield will be loaded from cookie

**Comment by gehlen** [comment]
status?

**Comment by joosth** [comment]
Fixed in commit ab3ed8a00c90c585aa3460f02b7f39a2291851d9
