### ISSUE TITLE
17.10RC1: download attachment on a request form

### ISSUE THREAD

**Issue by gehlen** [joosth/wfp-forms#11]
Start a new "Ad hoc task" dialog, the first tab is displaying a set of buttons:
![image](https://user-images.githubusercontent.com/432016/33075112-c05fb680-cec8-11e7-9416-b533c15fa9aa.png)

Clicking the "Download" button is resulting in a JSON error message (in a new browser tab):
![image](https://user-images.githubusercontent.com/432016/33075187-ef3990fc-cec8-11e7-9b0a-48f94cebd534.png)

Why is there a download button anyway?

**Comment by hwinwuzhere** [comment]
This issue is already resolved and will soon be pushed to develop! :)
