### ISSUE TITLE
17.10RC1: NullPointerException when opening a show form

### ISSUE THREAD

**Issue by gehlen** [joosth/wfp-forms#12]
Create a new "Ad hoc task", after creating it you'll have a new task (of course).
Do not handle the task, but open the show form for this document, it will result in a NullPointerException (wfp-forms log):
> ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [POST] /forms/form/validate - parameters:
value: 
label: 
formName: show
processName: Adhoc
documentId: 18
Cannot get property 'header' on null object. Stacktrace follows:
Message: Cannot get property 'header' on null object
    Line | Method
|    395 | validateAll  in org.workflow4people.validator.ValidatorDelegate
|    162 | validateForm in org.open_t.forms.ValidatorService
|    411 | validate . . in org.workflow4people.forms.services.WfpFormService
|    232 | validate     in org.workflow4people.forms.FormController
|   1142 | runWorker .  in java.util.concurrent.ThreadPoolExecutor
|    617 | run          in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . .  in java.lang.Thread

**Comment by hwinwuzhere** [comment]
Issue has been resolved in the latest develop commit.
