### ISSUE TITLE
Exception occurs while manualy navigating to a nonexistent tasklist

### ISSUE THREAD

**Issue by gehlen** [joosth/wfp-forms#3]
After login, go to "http://localhost:8084/forms/list/tasklist/test".. ("test" is not an existing list..)
It would be nice to receive a message about this, all we have is a not-working tasklist-page with JS errors.

GroovyCastException occurred when processing request: [POST] /forms/list/jsonlist - parameters:
iSortCol_0: 0
bRegex: false
listName: test
sSearch_0: 
sSearch_1: 
sSearch: 
iSortingCols: 1
mDataProp_0: 0
mDataProp_1: 1
bSortable_1: false
bSearchable_1: true
bSearchable_0: true
sSortDir_0: asc
bSortable_0: false
iDisplayStart: 0
sColumns: 
iColumns: 2
iDisplayLength: 10
sEcho: 1
bRegex_0: false
bRegex_1: false
Cannot cast object '[:]' with class 'groovy.util.ConfigObject' to class 'groovy.lang.Closure' due to: groovy.lang.GroovyRuntimeException: failed to invoke constructor: public groovy.lang.Closure(java.lang.Object) with arguments: [[:]] reason: java.lang.InstantiationException. Stacktrace follows:
Message: Cannot cast object '[:]' with class 'groovy.util.ConfigObject' to class 'groovy.lang.Closure' due to: groovy.lang.GroovyRuntimeException: failed to invoke constructor: public groovy.lang.Closure(java.lang.Object) with arguments: [[:]] reason: java.lang.InstantiationException
    Line | Method
->>   96 | jsonlist  in org.workflow4people.forms.ListController
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run       in java.lang.Thread

**Comment by joosth** [comment]
Check added.
