### ISSUE TITLE
Don't subset facetfields on tasklists / documentlists after a search..

### ISSUE THREAD

**Issue by gehlen** [joosth/wfp-forms#5]
If you use the searchfilter to search for example for clientName "Horward" other searchfields containing type facetfields will be refreshed and will only receive a subset of the all the information that is available..

This is not user friendly.

**Comment by joosth** [comment]
The whole idea of facets is to limit the scope of the next search. So this functions as designed. Showing facets values that will lead to zero results when selected as you are asking is even more user-unfriendly.
