### ISSUE TITLE
Facetfields splitted in words in searchfilter

### ISSUE THREAD

**Issue by gehlen** [joosth/wfp-forms#6]
Each option in a searchfilter facetfield is containing a word from the whole value..
For example "What does the fox say" will be displayed as options:
- what
- does
- the
- fox
- say

This is not user friendly..

**Comment by joosth** [comment]
You need to set up a non-tokenized Solr field for facets. See "Field-Value Faceting Parameters" in the Solr documentation at http://apache.cs.uu.nl/lucene/solr/ref-guide/apache-solr-ref-guide-6.1.pdf
